type: "dinov3"
enabled: True
repo_path: "C:\\Users\\ulloa\\OneDrive\\Desktop\\Practicas\\projectes\\dinov3"
name: "dinov3_vits16"
weights: "dinov3_vits16_weights.pth"
freeze: True
regularization: True
adapter_hidden_dims: []
image_dim: 256
embed_dim: 384
